"""add user_id to categories

Revision ID: 4e38a349b85c
Revises: b7c01f2deb30
Create Date: 2025-11-18 12:23:20.912324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e38a349b85c'
down_revision = 'b7c01f2deb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Get the first user ID to assign to existing categories
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1")).fetchone()
    if result:
        first_user_id = result[0]
        # Update existing categories with the first user ID
        op.execute(f"UPDATE categories SET user_id = {first_user_id} WHERE user_id IS NULL")

    # Now make it not null, drop old constraint, and add new constraints
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.drop_constraint('categories_name_key', type_='unique')
        batch_op.create_unique_constraint('unique_category_name_per_user', ['name', 'user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_category_name_per_user', type_='unique')
        batch_op.create_unique_constraint('categories_name_key', ['name'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
