"""add user_id to expenses

Revision ID: b7c01f2deb30
Revises: 36ce89f83dfe
Create Date: 2025-11-18 12:18:51.841659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c01f2deb30'
down_revision = '36ce89f83dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Get the first user ID to assign to existing expenses
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1")).fetchone()
    if result:
        first_user_id = result[0]
        # Update existing expenses with the first user ID
        op.execute(f"UPDATE expenses SET user_id = {first_user_id} WHERE user_id IS NULL")

    # Now make it not null and add foreign key
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
